{% set name = "scikit-fmm" %}
{% set version = "2024.9.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aba86ab5e5efeb4d221fbc6908a1e044b909612a72f6121ffd09e5b1823e8e1e

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - meson-python
    - python-build
  run:
    - python

test:
  requires:
    - pip
  imports:
    - skfmm
  commands:
    - pip check
    - test $(pip list | grep "scikit-fmm " | wc -l) -eq 1  # [unix]

about:
  home: https://github.com/scikit-fmm/scikit-fmm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: scikit-fmm is a Python extension module which implements the fast marching method.

  description: |
    scikit-fmm is a Python extension module which implements the fast marching method.
    Signed distance functions, Travel time transforms (solutions to the Eikonal equation), Extension velocities
  doc_url: https://scikit-fmm.readthedocs.io
  dev_url: https://github.com/scikit-fmm/scikit-fmm

extra:
  recipe-maintainers:
    - jan-janssen
    - xylar
