travis:
  secure:
    BINSTAR_TOKEN: J25As9jgekRDqB3VVGWJK5a4nH4Ds3LTvmJE3yQkE6dM463/Ozg7IVM8o5Y10EUyKh3a1LiffdTs+IhxSm99MjwD042m73EgAdc/SwN4+YO9uAKD7Lb29Dm+hwVsFNSG5fYof0DnS8q8Rl5KYExGL3/5ZU4PlBIBvNqXWF3QdB81VKYtatJ05PHZmPVY8XiwPeM6EIvysxakAF9WdTNrj4UHaJyIpzZsTTDLHTP59TZ5ZXi2vYkT8kwJGPjzNpiN+bOy2uwcQWpzHbgI4EGO/J9o93Ae+0VmJOAe1uH2nNLXN5nX0bht5dx7dOAK3v270cBm4Fl7xvl1pPAmzvl7gMaf8whOOthniur78+OFa/RAFv0NOxQdv34EAwAMcUQ3TMGmuzKdyYo13UslPEnM+a7K0BH+HHkQ7rvB2blVlOtnL6jyjozwzx/4jquC01r9hYe1ZUv6WeeNloiaVIg8fcYo525ltjVV903sL9fLxoREGsMZQB7i2xVauNkwxFjMbqZGQY2z/wsZgGPHZfw55wpfS3Rx6D9nDRavR2yK8RKw9bW9EILUXJdrPbhUxtSi2TeBdgNeYD6ajBrvWUEc+63MEvUgX1bpdzUMAQhsb76ftHXgB0z7n1/FqVvISkKoYV1ZlHZymqvN07z+u6ASoe0vSgtavPByCQA+D8JbEto=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
